package cl.rramirez.dvdstore.datos.hibernate.maps;
// Generated 11-12-2012 01:06:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store  implements java.io.Serializable {


     private Byte storeId;
     private Staff staff;
     private Address address;
     private Date lastUpdate;
     private Set<Inventory> inventories = new HashSet<Inventory>(0);
     private Set<Customer> customers = new HashSet<Customer>(0);
     private Set<Staff> staffs = new HashSet<Staff>(0);

    public Store() {
    }

	
    public Store(Staff staff, Address address, Date lastUpdate) {
        this.staff = staff;
        this.address = address;
        this.lastUpdate = lastUpdate;
    }
    public Store(Staff staff, Address address, Date lastUpdate, Set<Inventory> inventories, Set<Customer> customers, Set<Staff> staffs) {
       this.staff = staff;
       this.address = address;
       this.lastUpdate = lastUpdate;
       this.inventories = inventories;
       this.customers = customers;
       this.staffs = staffs;
    }
   
    public Byte getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(Byte storeId) {
        this.storeId = storeId;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set<Inventory> getInventories() {
        return this.inventories;
    }
    
    public void setInventories(Set<Inventory> inventories) {
        this.inventories = inventories;
    }
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }




}


